// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqhgXeGfTE3ktEdqX40Hns_EfKg9K4ZZc',
    appId: '1:232873021424:web:4640686f5d6fef0c815735',
    messagingSenderId: '232873021424',
    projectId: 'mycosmi',
    authDomain: 'mycosmi.firebaseapp.com',
    storageBucket: 'mycosmi.appspot.com',
    measurementId: 'G-6780D8M21Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVrrqcWUUnx0Sx22_mnmxIw5I-KMQykQ0',
    appId: '1:232873021424:android:d123827e90f118d8815735',
    messagingSenderId: '232873021424',
    projectId: 'mycosmi',
    storageBucket: 'mycosmi.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDvI8_SWG3fJy_Oltft-t8DhWGU3DwIpZM',
    appId: '1:232873021424:ios:76d07825706ada2d815735',
    messagingSenderId: '232873021424',
    projectId: 'mycosmi',
    storageBucket: 'mycosmi.appspot.com',
    iosBundleId: 'com.example.mycosmi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDvI8_SWG3fJy_Oltft-t8DhWGU3DwIpZM',
    appId: '1:232873021424:ios:e0859af851b02c38815735',
    messagingSenderId: '232873021424',
    projectId: 'mycosmi',
    storageBucket: 'mycosmi.appspot.com',
    iosBundleId: 'com.example.mycosmi.RunnerTests',
  );
}
